In [3]:
import torch

inputs = torch.tensor([
    [0.43, 0.15, 0.89], # Your (x^1)
    [0.55, 0.87, 0.66], # jpurney (x^2)
    [0.57, 0.85, 0.64], # starts (x^3)
    [0.22, 0.58, 0.33], # with (x^4)
    [0.77, 0.25, 0.10], # one (x^5)
    [0.05, 0.80, 0.55] # step (x^6)
])

In [4]:
query = inputs[1] # jpurney (x^2)

atten_scores_2 = torch.empty(inputs.shape[0])  # 各単語ベクトルとクエリベクトルの内積を計算
for i, x_i in enumerate(inputs):
    atten_scores_2[i] = torch.dot(x_i, query)
print(atten_scores_2)

tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865])


In [5]:
attn_weights_2_tmp = atten_scores_2 / atten_scores_2.sum()
print(attn_weights_2_tmp)
print("Sum: ", attn_weights_2_tmp.sum())

tensor([0.1455, 0.2278, 0.2249, 0.1285, 0.1077, 0.1656])
Sum:  tensor(1.0000)


In [6]:
def softmax_naive(x):
    return torch.exp(x) / torch.exp(x).sum(dim=0)

attn_weights_2_naive = softmax_naive(atten_scores_2)
print(attn_weights_2_naive)
print("Sum: ", attn_weights_2_naive.sum())

tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])
Sum:  tensor(1.)


In [7]:
attn_weights_2 = torch.softmax(atten_scores_2, dim=0)
print(attn_weights_2)
print("Sum: ", attn_weights_2.sum())

tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])
Sum:  tensor(1.)
